export const all = [
  {
    id: 1,
    title: "Like Crazy",
    artist: "Jimin of BTS",
    album: "Face",
    cover: "images/face.png",
    audio: "audios/like_crazy.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "gray"],
  },
  {
    id: 2,
    title: "Take Two",
    artist: "BTS",
    album: "Take Two",
    cover: "images/bts2.jpeg",
    audio: "audios/take_two.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "blueviolet"],
  },
  {
    id: 3,
    title: "Money",
    artist: "LISA",
    album: "MONEY",
    cover: "images/money.jpg",
    audio: "audios/money.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "red"],
  },
  {
    id: 4,
    title: "Slow Dancing",
    artist: "V of BTS",
    album: "LAYOVER",
    cover: "images/layover.jpg",
    audio: "audios/slow_dancing.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "gray"],
  },
  {
    id: 5,
    title: "Over",
    artist: "Luke Daye",
    album: "",
    cover: "images/over.jpg",
    audio: "audios/over.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "white"],
  },
  {
    id: 6,
    title: "Please don't change",
    artist: "Jungkook of BTS",
    album: "GOLDEN",
    cover: "images/back.jpg",
    audio: "audios/please_don_t_change.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["darkgreen", "gold"],
  },
  {
    id: 7,
    title: "Love Me Again",
    artist: "V of BTS",
    album: "LAYOVER",
    cover: "images/vna.jpg",
    audio: "audios/love_me_again.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["silver", "gold"],
  },
  {
    id: 8,
    title: "Karma",
    artist: "Summer Walker",
    album: "",
    cover: "images/vintage.jpg",
    audio: "audios/karma.mp3",
    onLoop: false,
    isPlaying: false,
    liked: false,
    colors: ["black", "white"],
  },
];
